parameters:
#    eventhor_main.example.class: Eventhor\Bundle\MainBundle\Example

services:
#    eventhor_main.example:
#        class: %eventhor_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
